# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_patientDataWindow(object):
    def setupUi(self, patientDataWindow):
        patientDataWindow.setObjectName("patientDataWindow")
        patientDataWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(patientDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.patientList_combo = QtWidgets.QComboBox(self.centralwidget)
        self.patientList_combo.setGeometry(QtCore.QRect(250, 30, 321, 31))
        self.patientList_combo.setObjectName("patientList_combo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 51))

        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setIndent(1)
        self.label_2.setObjectName("label_2")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(230, 110, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.name_lbl.setFont(font)
        self.name_lbl.setText("")
        self.name_lbl.setObjectName("name_lbl")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setIndent(1)
        self.label_4.setObjectName("label_4")
        self.class_lbl = QtWidgets.QLabel(self.centralwidget)
        self.class_lbl.setGeometry(QtCore.QRect(250, 190, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.class_lbl.setFont(font)
        self.class_lbl.setText("")
        self.class_lbl.setObjectName("class_lbl")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setIndent(1)
        self.label_5.setObjectName("label_5")
        self.age_lbl = QtWidgets.QLabel(self.centralwidget)
        self.age_lbl.setGeometry(QtCore.QRect(80, 260, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.age_lbl.setFont(font)
        self.age_lbl.setText("")
        self.age_lbl.setObjectName("age_lbl")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setIndent(1)
        self.label_6.setObjectName("label_6")
        self.height_lbl = QtWidgets.QLabel(self.centralwidget)
        self.height_lbl.setGeometry(QtCore.QRect(120, 330, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.height_lbl.setFont(font)
        self.height_lbl.setText("")
        self.height_lbl.setObjectName("height_lbl")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 330, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setIndent(1)
        self.label_7.setObjectName("label_7")
        self.weight_lbl = QtWidgets.QLabel(self.centralwidget)
        self.weight_lbl.setGeometry(QtCore.QRect(550, 330, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.weight_lbl.setFont(font)
        self.weight_lbl.setText("")
        self.weight_lbl.setObjectName("weight_lbl")
        self.analysis_btn = QtWidgets.QPushButton(self.centralwidget)
        self.analysis_btn.setGeometry(QtCore.QRect(260, 460, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.analysis_btn.setFont(font)
        self.analysis_btn.setStyleSheet("background-color: rgb(146, 208, 80);")
        self.analysis_btn.setObjectName("analysis_btn")
        patientDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(patientDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        patientDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(patientDataWindow)
        self.statusbar.setObjectName("statusbar")
        patientDataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(patientDataWindow)
        QtCore.QMetaObject.connectSlotsByName(patientDataWindow)

    def retranslateUi(self, patientDataWindow):
        _translate = QtCore.QCoreApplication.translate
        patientDataWindow.setWindowTitle(_translate("patientDataWindow", "Patient Data"))
        self.label.setText(_translate("patientDataWindow", "PATIENT LIST"))
        self.label_2.setText(_translate("patientDataWindow", "PATIENT NAME:"))
        self.label_4.setText(_translate("patientDataWindow", "CLASSIFICATION:"))
        self.label_5.setText(_translate("patientDataWindow", "Age:"))
        self.label_6.setText(_translate("patientDataWindow", "Height:"))
        self.label_7.setText(_translate("patientDataWindow", "Weight:"))
        self.analysis_btn.setText(_translate("patientDataWindow", "View Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    patientDataWindow = QtWidgets.QMainWindow()
    ui = Ui_patientDataWindow()
    ui.setupUi(patientDataWindow)
    patientDataWindow.show()
    sys.exit(app.exec_())
