# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valueEdit.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editValues(object):
    def setupUi(self, editValues):
        editValues.setObjectName("editValues")
        editValues.resize(644, 778)
        self.centralwidget = QtWidgets.QWidget(editValues)
        self.centralwidget.setObjectName("centralwidget")
        self.lowRespiMax_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.lowRespiMax_blank.setGeometry(QtCore.QRect(190, 100, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lowRespiMax_blank.setFont(font)
        self.lowRespiMax_blank.setObjectName("lowRespiMax_blank")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.lowRespiMin_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.lowRespiMin_blank.setGeometry(QtCore.QRect(430, 100, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lowRespiMin_blank.setFont(font)
        self.lowRespiMin_blank.setObjectName("lowRespiMin_blank")
        self.highRespiMax_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.highRespiMax_blank.setGeometry(QtCore.QRect(430, 240, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.highRespiMax_blank.setFont(font)
        self.highRespiMax_blank.setObjectName("highRespiMax_blank")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 240, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.highRespiMin_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.highRespiMin_blank.setGeometry(QtCore.QRect(190, 240, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.highRespiMin_blank.setFont(font)
        self.highRespiMin_blank.setObjectName("highRespiMin_blank")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("\n"
"color: rgb(170, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.highHeartMin_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.highHeartMin_blank.setGeometry(QtCore.QRect(190, 570, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.highHeartMin_blank.setFont(font)
        self.highHeartMin_blank.setObjectName("highHeartMin_blank")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_7.setObjectName("label_7")
        self.lowHeartMin_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.lowHeartMin_blank.setGeometry(QtCore.QRect(430, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lowHeartMin_blank.setFont(font)
        self.lowHeartMin_blank.setObjectName("lowHeartMin_blank")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 510, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("\n"
"color: rgb(170, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(320, 430, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(320, 570, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.lowHeartMax_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.lowHeartMax_blank.setGeometry(QtCore.QRect(190, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lowHeartMax_blank.setFont(font)
        self.lowHeartMax_blank.setObjectName("lowHeartMax_blank")
        self.highHeartMax_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.highHeartMax_blank.setGeometry(QtCore.QRect(430, 570, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.highHeartMax_blank.setFont(font)
        self.highHeartMax_blank.setObjectName("highHeartMax_blank")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 430, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.saveValues_btn = QtWidgets.QPushButton(self.centralwidget)
        self.saveValues_btn.setGeometry(QtCore.QRect(260, 660, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveValues_btn.setFont(font)
        self.saveValues_btn.setStyleSheet("background-color: rgb(146, 208, 80);")
        self.saveValues_btn.setObjectName("saveValues_btn")
        editValues.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(editValues)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 26))
        self.menubar.setObjectName("menubar")
        editValues.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(editValues)
        self.statusbar.setObjectName("statusbar")
        editValues.setStatusBar(self.statusbar)

        self.retranslateUi(editValues)
        QtCore.QMetaObject.connectSlotsByName(editValues)

    def retranslateUi(self, editValues):
        _translate = QtCore.QCoreApplication.translate
        editValues.setWindowTitle(_translate("editValues", "Edit Values for Abnormality"))
        self.label.setText(_translate("editValues", "Low Respiration Rate"))
        self.label_2.setText(_translate("editValues", "Lower than"))
        self.label_3.setText(_translate("editValues", "down to"))
        self.label_4.setText(_translate("editValues", "up to"))
        self.label_5.setText(_translate("editValues", "Higher than"))
        self.label_6.setText(_translate("editValues", "High Respiration Rate"))
        self.label_7.setText(_translate("editValues", "Low Heart Rate"))
        self.label_8.setText(_translate("editValues", "High Heart Rate"))
        self.label_9.setText(_translate("editValues", "down to"))
        self.label_10.setText(_translate("editValues", "up to"))
        self.label_11.setText(_translate("editValues", "Lower than"))
        self.label_12.setText(_translate("editValues", "Higher than"))
        self.saveValues_btn.setText(_translate("editValues", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editValues = QtWidgets.QMainWindow()
    ui = Ui_editValues()
    ui.setupUi(editValues)
    editValues.show()
    sys.exit(app.exec_())
